// sidebars.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    // Quickstart 独立放在第一位
    {
      type: 'doc',
      id: 'quickstart',
      label: 'Quickstart',
    },
    // Overview 目录
    {
      type: 'category',
      label: 'Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    // Products 目录
    {
      type: 'category',
      label: 'Products',
      items: [
        {
          type: 'autogenerated',
          dirName: 'products',
        },
      ],
    },
    // Trading 目录
    {
      type: 'category',
      label: 'Trading',
      items: [
        {
          type: 'autogenerated',
          dirName: 'trading',
        },
      ],
    },
    // Market Data 目录
    {
      type: 'category',
      label: 'Market Data',
      items: [
        {
          type: 'autogenerated',
          dirName: 'market-data',
        },
      ],
    },
    // Integration 目录
    {
      type: 'category',
      label: 'Integration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integration',
        },
      ],
    },
    // Changelog 放在最后
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
  ],
};

module.exports = sidebars;
